# Generated by Django 2.1.2 on 2018-11-16 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('initialcredit', models.IntegerField()),
                ('aftercredit', models.IntegerField()),
                ('getcredit', models.IntegerField()),
                ('organisation', models.CharField(choices=[('Blood Bank', 'Blood Bank'), ('Apollo Hospitals, Greams Road.', 'Apollo Hospitals, Greams Road.'), ('Chettinad Health City, Kelambakkam.', 'Chettinad Health City, Kelambakkam.')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('walletid', models.AutoField(primary_key=True, serialize=False)),
                ('credit', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.Wallet'),
        ),
    ]
