# Generated by Django 2.1 on 2018-11-16 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_remove_transaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='credits.Wallet'),
            preserve_default=False,
        ),
    ]
