# Generated by Django 2.1.2 on 2018-12-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodcamp', '0002_auto_20181117_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodvolunteer',
            name='nickname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
