# Generated by Django 2.1.2 on 2018-11-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181117_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='donation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
