# Generated by Django 2.1.2 on 2018-11-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181117_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='house',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='landmark',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='locality',
            field=models.CharField(max_length=400),
        ),
    ]
