# Generated by Django 2.1.3 on 2018-12-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20181206_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='landmark',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
