# Generated by Django 2.1.3 on 2018-12-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20181212_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='birth',
            field=models.DateField(),
        ),
    ]
