# Generated by Django 2.1.2 on 2018-11-17 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestblood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestor',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.City'),
        ),
        migrations.AlterField(
            model_name='requestor',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.State'),
        ),
    ]
