# Generated by Django 2.1.2 on 2018-11-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('Hospitalid', models.AutoField(primary_key=True, serialize=False)),
                ('Hospital_name', models.CharField(max_length=100)),
                ('Hospital_address', models.CharField(max_length=1000)),
                ('Hospital_location', models.IntegerField(verbose_name=8)),
            ],
        ),
    ]
