# Generated by Django 2.1.2 on 2018-12-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='Hospital_location',
        ),
    ]
